### ISSUE TITLE
Maniac don't work

### ISSUE THREAD

**Issue by Hide-User** [LW2904/maniac#34]
Hi i use Maniac.exe and don't work when i did everything i seemed to do.
![Capture](https://user-images.githubusercontent.com/62671486/80011989-ea75b980-84cc-11ea-83e8-5c1e9b33c1a1.PNG)

**Comment by LW2904** [comment]
I'm afraid my french isn't particularly good but am I right in deducing that the error simply says something along the lines of "the application couldn't start correctly (0x0...), press okay to close it"?

**Comment by Hide-User** [comment]
No there is no other message and I just fixed the dll just before

**Comment by LW2904** [comment]
I'll look into this tomorrow and get back to you then. This project has
been unmaintained for a while so there are quite a number of issues to
stamp out.

**Comment by Sensest** [comment]
Yeah, it just says that, I have the same issue when I tried it today. I was missing the libwinpthread-1 dll too, so I got that and then the error changed to this one.
Just found your stuff, looks great!

**Comment by LW2904** [comment]
> I was missing the libwinpthread-1 dll too, so I got that and then the error changed to this one.
Just out of curiosity, what did you do to resolve the libwinpthread error?

**Comment by Sensest** [comment]
I'm not a genius or anything so I just look'd up the dll and placed it in System32... Maybe I got it wrong and that's why the problem persists?

**Comment by LW2904** [comment]
That's actually a pretty good hotfix, should've thought about that -- thanks! Hopefully, v0.3.10 fixes the pthread issue but I suppose that's a decent workaround if it doesn't. Really want to get around to fixing all the other stuff.

**Comment by LW2904** [comment]
@Hide-User could you try running build [v0.3.10](https://github.com/LW2904/maniac/releases/tag/v0.3.10)? 0xc000007b seems to be one of those unhelpful "catch-all" error codes so I don't have anything more specific than that yet, sorry.

**Comment by Sensest** [comment]
Hey, the new version fixed it for me, no more 0xc000007b. Tried to run it with a random map and got this error:
failed to parse beatmap (C:\Users\ian00\AppData\Local\osu!\Songs\831569 Chroma - Made In Love\Chroma - Made In Love (Lude) [Arpia's Advanced].osu)
an error occured while playing, there's likely additional error output above
Weird thing is, that wasn't the map I tried it with nor did it change after I restarted osu! / maniac... Should I open a new issue for this or are you already working on this?, thanks for the fast responses!

**Comment by LW2904** [comment]
The broken map parsing is already tracked in #33. Looks like what you're experiencing has something to do with the process of _finding_ the map though, which is another beast entirely.

I can't reproduce this on my machines so I won't open one, but if you like you could open an issue in regards to that.

**Comment by Sensest** [comment]
I'll make sure that's the case later and maybe I'll open an issue... I feel like this could be a problem only for my machine that COULD possibly be fixed (for me) when you get the map parsing working... I'll stop commenting in this issue since it wasn't even mine to begin with, godspeed man

**Comment by LW2904** [comment]
So I finally got around to setting up a clean windows VM and I can't reproduce this issue. I'll take that to mean that it's resolved, feel free to ping me if it's not.

PS: @Sensest [v0.4.0](https://github.com/LW2904/maniac/releases/tag/v0.4.0) should fix the map parsing issue on most maps, see #33 for details.
